// protoc --proto_path=. --go_out=plugins=grpc:. socialite.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: socialite.proto

package socialite

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socialite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_socialite_proto_rawDescGZIP(), []int{0}
}

type NoParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_socialite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_socialite_proto_rawDescGZIP(), []int{1}
}

type WxLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WxLoginRequest) Reset() {
	*x = WxLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginRequest) ProtoMessage() {}

func (x *WxLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_socialite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginRequest.ProtoReflect.Descriptor instead.
func (*WxLoginRequest) Descriptor() ([]byte, []int) {
	return file_socialite_proto_rawDescGZIP(), []int{2}
}

type WxLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WxLoginResponse) Reset() {
	*x = WxLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginResponse) ProtoMessage() {}

func (x *WxLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socialite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginResponse.ProtoReflect.Descriptor instead.
func (*WxLoginResponse) Descriptor() ([]byte, []int) {
	return file_socialite_proto_rawDescGZIP(), []int{3}
}

type WxJsLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // js授权获得的 code
}

func (x *WxJsLoginRequest) Reset() {
	*x = WxJsLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialite_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxJsLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxJsLoginRequest) ProtoMessage() {}

func (x *WxJsLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_socialite_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxJsLoginRequest.ProtoReflect.Descriptor instead.
func (*WxJsLoginRequest) Descriptor() ([]byte, []int) {
	return file_socialite_proto_rawDescGZIP(), []int{4}
}

func (x *WxJsLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// WxJsLogin 微信登录
type WxJsLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsLogin int32  `protobuf:"varint,1,opt,name=is_login,json=isLogin,proto3" json:"is_login,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *WxJsLoginResponse) Reset() {
	*x = WxJsLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialite_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxJsLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxJsLoginResponse) ProtoMessage() {}

func (x *WxJsLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socialite_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxJsLoginResponse.ProtoReflect.Descriptor instead.
func (*WxJsLoginResponse) Descriptor() ([]byte, []int) {
	return file_socialite_proto_rawDescGZIP(), []int{5}
}

func (x *WxJsLoginResponse) GetIsLogin() int32 {
	if x != nil {
		return x.IsLogin
	}
	return 0
}

func (x *WxJsLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// WxJsConfig 微信基础jsSDK接口
type WxJsConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid     string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Noncestr  string `protobuf:"bytes,4,opt,name=noncestr,proto3" json:"noncestr,omitempty"`
}

func (x *WxJsConfigResponse) Reset() {
	*x = WxJsConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socialite_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxJsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxJsConfigResponse) ProtoMessage() {}

func (x *WxJsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socialite_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxJsConfigResponse.ProtoReflect.Descriptor instead.
func (*WxJsConfigResponse) Descriptor() ([]byte, []int) {
	return file_socialite_proto_rawDescGZIP(), []int{6}
}

func (x *WxJsConfigResponse) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *WxJsConfigResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WxJsConfigResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WxJsConfigResponse) GetNoncestr() string {
	if x != nil {
		return x.Noncestr
	}
	return ""
}

var File_socialite_proto protoreflect.FileDescriptor

var file_socialite_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x22, 0x0c, 0x0a, 0x0a,
	0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x6f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x10, 0x0a, 0x0e, 0x57, 0x78, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x57, 0x78, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x57, 0x78,
	0x4a, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x44, 0x0a, 0x11, 0x57, 0x78, 0x4a, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x12, 0x57, 0x78, 0x4a,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x72, 0x32, 0x9f, 0x01,
	0x0a, 0x10, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x57, 0x78, 0x4a, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x1b, 0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x57, 0x78, 0x4a, 0x73,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x57, 0x78, 0x4a, 0x73, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a,
	0x57, 0x78, 0x4a, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x2e, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x1d,
	0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x57, 0x78, 0x4a, 0x73, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x3b, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_socialite_proto_rawDescOnce sync.Once
	file_socialite_proto_rawDescData = file_socialite_proto_rawDesc
)

func file_socialite_proto_rawDescGZIP() []byte {
	file_socialite_proto_rawDescOnce.Do(func() {
		file_socialite_proto_rawDescData = protoimpl.X.CompressGZIP(file_socialite_proto_rawDescData)
	})
	return file_socialite_proto_rawDescData
}

var file_socialite_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_socialite_proto_goTypes = []interface{}{
	(*OkResponse)(nil),         // 0: socialite.OkResponse
	(*NoParam)(nil),            // 1: socialite.NoParam
	(*WxLoginRequest)(nil),     // 2: socialite.WxLoginRequest
	(*WxLoginResponse)(nil),    // 3: socialite.WxLoginResponse
	(*WxJsLoginRequest)(nil),   // 4: socialite.WxJsLoginRequest
	(*WxJsLoginResponse)(nil),  // 5: socialite.WxJsLoginResponse
	(*WxJsConfigResponse)(nil), // 6: socialite.WxJsConfigResponse
}
var file_socialite_proto_depIdxs = []int32{
	4, // 0: socialite.SocialiteService.WxJsLogin:input_type -> socialite.WxJsLoginRequest
	1, // 1: socialite.SocialiteService.WxJsConfig:input_type -> socialite.NoParam
	5, // 2: socialite.SocialiteService.WxJsLogin:output_type -> socialite.WxJsLoginResponse
	6, // 3: socialite.SocialiteService.WxJsConfig:output_type -> socialite.WxJsConfigResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_socialite_proto_init() }
func file_socialite_proto_init() {
	if File_socialite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_socialite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socialite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socialite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socialite_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socialite_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxJsLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socialite_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxJsLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socialite_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxJsConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_socialite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_socialite_proto_goTypes,
		DependencyIndexes: file_socialite_proto_depIdxs,
		MessageInfos:      file_socialite_proto_msgTypes,
	}.Build()
	File_socialite_proto = out.File
	file_socialite_proto_rawDesc = nil
	file_socialite_proto_goTypes = nil
	file_socialite_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SocialiteServiceClient is the client API for SocialiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SocialiteServiceClient interface {
	//  rpc WxLogin (WxLoginRequest) returns (WxLoginResponse) {}
	//  rpc AppLogin (WxLoginRequest) returns (WxLoginResponse) {}
	WxJsLogin(ctx context.Context, in *WxJsLoginRequest, opts ...grpc.CallOption) (*WxJsLoginResponse, error)
	WxJsConfig(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*WxJsConfigResponse, error)
}

type socialiteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialiteServiceClient(cc grpc.ClientConnInterface) SocialiteServiceClient {
	return &socialiteServiceClient{cc}
}

func (c *socialiteServiceClient) WxJsLogin(ctx context.Context, in *WxJsLoginRequest, opts ...grpc.CallOption) (*WxJsLoginResponse, error) {
	out := new(WxJsLoginResponse)
	err := c.cc.Invoke(ctx, "/socialite.SocialiteService/WxJsLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialiteServiceClient) WxJsConfig(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*WxJsConfigResponse, error) {
	out := new(WxJsConfigResponse)
	err := c.cc.Invoke(ctx, "/socialite.SocialiteService/WxJsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialiteServiceServer is the server API for SocialiteService service.
type SocialiteServiceServer interface {
	//  rpc WxLogin (WxLoginRequest) returns (WxLoginResponse) {}
	//  rpc AppLogin (WxLoginRequest) returns (WxLoginResponse) {}
	WxJsLogin(context.Context, *WxJsLoginRequest) (*WxJsLoginResponse, error)
	WxJsConfig(context.Context, *NoParam) (*WxJsConfigResponse, error)
}

// UnimplementedSocialiteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSocialiteServiceServer struct {
}

func (*UnimplementedSocialiteServiceServer) WxJsLogin(context.Context, *WxJsLoginRequest) (*WxJsLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WxJsLogin not implemented")
}
func (*UnimplementedSocialiteServiceServer) WxJsConfig(context.Context, *NoParam) (*WxJsConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WxJsConfig not implemented")
}

func RegisterSocialiteServiceServer(s *grpc.Server, srv SocialiteServiceServer) {
	s.RegisterService(&_SocialiteService_serviceDesc, srv)
}

func _SocialiteService_WxJsLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WxJsLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialiteServiceServer).WxJsLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socialite.SocialiteService/WxJsLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialiteServiceServer).WxJsLogin(ctx, req.(*WxJsLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialiteService_WxJsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialiteServiceServer).WxJsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socialite.SocialiteService/WxJsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialiteServiceServer).WxJsConfig(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _SocialiteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "socialite.SocialiteService",
	HandlerType: (*SocialiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WxJsLogin",
			Handler:    _SocialiteService_WxJsLogin_Handler,
		},
		{
			MethodName: "WxJsConfig",
			Handler:    _SocialiteService_WxJsConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "socialite.proto",
}
