// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: assess.proto

package assess

import (
	context "context"
	apis "git.pmx.cn/hci/microservice-app/proto/apis"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{0}
}

type NoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoRequest) Reset() {
	*x = NoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoRequest) ProtoMessage() {}

func (x *NoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoRequest.ProtoReflect.Descriptor instead.
func (*NoRequest) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{1}
}

type SimpleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    map[string]*apis.Pair `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SimpleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SimpleResponse) GetData() map[string]*apis.Pair {
	if x != nil {
		return x.Data
	}
	return nil
}

type ScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone  string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SocialScore    string `protobuf:"bytes,1,opt,name=social_score,json=socialScore,proto3" json:"social_score,omitempty"`
	PostScore      string `protobuf:"bytes,2,opt,name=post_score,json=postScore,proto3" json:"post_score,omitempty"`
	FinancialScore string `protobuf:"bytes,3,opt,name=financial_score,json=financialScore,proto3" json:"financial_score,omitempty"`
	Mobile         string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	IdCard         string `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	UserId         string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreResponse) GetSocialScore() string {
	if x != nil {
		return x.SocialScore
	}
	return ""
}

func (x *ScoreResponse) GetPostScore() string {
	if x != nil {
		return x.PostScore
	}
	return ""
}

func (x *ScoreResponse) GetFinancialScore() string {
	if x != nil {
		return x.FinancialScore
	}
	return ""
}

func (x *ScoreResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ScoreResponse) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *ScoreResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BasicInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Income      float64 `protobuf:"fixed64,1,opt,name=income,proto3" json:"income,omitempty"`
	HouseHoldId int32   `protobuf:"varint,2,opt,name=house_hold_id,json=houseHoldId,proto3" json:"house_hold_id,omitempty"` // 户口性质ID
	HouseHold   string  `protobuf:"bytes,3,opt,name=house_hold,json=houseHold,proto3" json:"house_hold,omitempty"`
	MarriageId  int32   `protobuf:"varint,4,opt,name=marriage_id,json=marriageId,proto3" json:"marriage_id,omitempty"` // 婚姻状况 id
	Marriage    string  `protobuf:"bytes,5,opt,name=marriage,proto3" json:"marriage,omitempty"`
	FamilyId    int32   `protobuf:"varint,6,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // 家庭信息
	Family      string  `protobuf:"bytes,7,opt,name=family,proto3" json:"family,omitempty"`
	PoliticalId int32   `protobuf:"varint,8,opt,name=political_id,json=politicalId,proto3" json:"political_id,omitempty"`
	Political   string  `protobuf:"bytes,9,opt,name=political,proto3" json:"political,omitempty"` // 政治面貌
}

func (x *BasicInfoRequest) Reset() {
	*x = BasicInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicInfoRequest) ProtoMessage() {}

func (x *BasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicInfoRequest.ProtoReflect.Descriptor instead.
func (*BasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{5}
}

func (x *BasicInfoRequest) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *BasicInfoRequest) GetHouseHoldId() int32 {
	if x != nil {
		return x.HouseHoldId
	}
	return 0
}

func (x *BasicInfoRequest) GetHouseHold() string {
	if x != nil {
		return x.HouseHold
	}
	return ""
}

func (x *BasicInfoRequest) GetMarriageId() int32 {
	if x != nil {
		return x.MarriageId
	}
	return 0
}

func (x *BasicInfoRequest) GetMarriage() string {
	if x != nil {
		return x.Marriage
	}
	return ""
}

func (x *BasicInfoRequest) GetFamilyId() int32 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *BasicInfoRequest) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *BasicInfoRequest) GetPoliticalId() int32 {
	if x != nil {
		return x.PoliticalId
	}
	return 0
}

func (x *BasicInfoRequest) GetPolitical() string {
	if x != nil {
		return x.Political
	}
	return ""
}

type EducationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EducationLevelId   int32  `protobuf:"varint,1,opt,name=educationLevelId,proto3" json:"educationLevelId,omitempty"`     //	int 	学历层次id
	EducationLevel     string `protobuf:"bytes,2,opt,name=educationLevel,proto3" json:"educationLevel,omitempty"`          // 	string 	学历层次
	AdmissionTime      string `protobuf:"bytes,3,opt,name=admissionTime,proto3" json:"admissionTime,omitempty"`            //	date 	入学时间
	GraduationTime     string `protobuf:"bytes,4,opt,name=graduationTime,proto3" json:"graduationTime,omitempty"`          //	date 	毕业时间
	SchoolName         string `protobuf:"bytes,5,opt,name=schoolName,proto3" json:"schoolName,omitempty"`                  // 	string 	学校名称
	ProfessionId       int32  `protobuf:"varint,6,opt,name=professionId,proto3" json:"professionId,omitempty"`             //	int 	专业id
	Profession         string `protobuf:"bytes,7,opt,name=profession,proto3" json:"profession,omitempty"`                  //	string 	专业
	EducationScienceId int32  `protobuf:"varint,8,opt,name=educationScienceId,proto3" json:"educationScienceId,omitempty"` //	int 	学位id
	EducationScience   string `protobuf:"bytes,9,opt,name=educationScience,proto3" json:"educationScience,omitempty"`      //	string 	学位
}

func (x *EducationRequest) Reset() {
	*x = EducationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EducationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EducationRequest) ProtoMessage() {}

func (x *EducationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EducationRequest.ProtoReflect.Descriptor instead.
func (*EducationRequest) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{6}
}

func (x *EducationRequest) GetEducationLevelId() int32 {
	if x != nil {
		return x.EducationLevelId
	}
	return 0
}

func (x *EducationRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *EducationRequest) GetAdmissionTime() string {
	if x != nil {
		return x.AdmissionTime
	}
	return ""
}

func (x *EducationRequest) GetGraduationTime() string {
	if x != nil {
		return x.GraduationTime
	}
	return ""
}

func (x *EducationRequest) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *EducationRequest) GetProfessionId() int32 {
	if x != nil {
		return x.ProfessionId
	}
	return 0
}

func (x *EducationRequest) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

func (x *EducationRequest) GetEducationScienceId() int32 {
	if x != nil {
		return x.EducationScienceId
	}
	return 0
}

func (x *EducationRequest) GetEducationScience() string {
	if x != nil {
		return x.EducationScience
	}
	return ""
}

type WorkinfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvinceId  int32  `protobuf:"varint,1,opt,name=provinceId,proto3" json:"provinceId,omitempty"`  //	int 	省份id
	Province    string `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`       //	string 	省份
	CityId      int32  `protobuf:"varint,3,opt,name=cityId,proto3" json:"cityId,omitempty"`          // 	int 	城市id
	City        string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`               //	string 	城市
	CompanyName string `protobuf:"bytes,5,opt,name=companyName,proto3" json:"companyName,omitempty"` //	string 	公司名称
	EntryTime   string `protobuf:"bytes,6,opt,name=entryTime,proto3" json:"entryTime,omitempty"`     //	date 	入职时间
	PositionId  int32  `protobuf:"varint,7,opt,name=positionId,proto3" json:"positionId,omitempty"`  // 	int 	岗位类别id
	Position    string `protobuf:"bytes,8,opt,name=position,proto3" json:"position,omitempty"`       //	string 	岗位类别
}

func (x *WorkinfoRequest) Reset() {
	*x = WorkinfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assess_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkinfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkinfoRequest) ProtoMessage() {}

func (x *WorkinfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assess_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkinfoRequest.ProtoReflect.Descriptor instead.
func (*WorkinfoRequest) Descriptor() ([]byte, []int) {
	return file_assess_proto_rawDescGZIP(), []int{7}
}

func (x *WorkinfoRequest) GetProvinceId() int32 {
	if x != nil {
		return x.ProvinceId
	}
	return 0
}

func (x *WorkinfoRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *WorkinfoRequest) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *WorkinfoRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WorkinfoRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *WorkinfoRequest) GetEntryTime() string {
	if x != nil {
		return x.EntryTime
	}
	return ""
}

func (x *WorkinfoRequest) GetPositionId() int32 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *WorkinfoRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

var File_assess_proto protoreflect.FileDescriptor

var file_assess_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x1a, 0x0a, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xb9, 0x01,
	0x0a, 0x0e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61,
	0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x43, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3d, 0x0a, 0x0c, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6c,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0xa0, 0x02, 0x0a, 0x10, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x72, 0x69, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x72, 0x69, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x72, 0x72, 0x69, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x72, 0x69, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6c, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x6f, 0x6c, 0x69, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x22, 0xf4, 0x02, 0x0a, 0x10, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x65, 0x64, 0x75, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x64, 0x75,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x61,
	0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x61, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x72, 0x61, 0x64, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x67, 0x72, 0x61, 0x64, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x68,
	0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a,
	0x12, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x65, 0x64, 0x75, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a,
	0x10, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x63, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xf5, 0x01, 0x0a, 0x0f, 0x57, 0x6f,
	0x72, 0x6b, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x32, 0xbd, 0x02, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x14, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e,
	0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x73, 0x73, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x53, 0x61, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0d, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x61, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e,
	0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x61,
	0x76, 0x65, 0x12, 0x17, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x73, 0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x3b, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_assess_proto_rawDescOnce sync.Once
	file_assess_proto_rawDescData = file_assess_proto_rawDesc
)

func file_assess_proto_rawDescGZIP() []byte {
	file_assess_proto_rawDescOnce.Do(func() {
		file_assess_proto_rawDescData = protoimpl.X.CompressGZIP(file_assess_proto_rawDescData)
	})
	return file_assess_proto_rawDescData
}

var file_assess_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_assess_proto_goTypes = []interface{}{
	(*OkResponse)(nil),       // 0: assess.OkResponse
	(*NoRequest)(nil),        // 1: assess.NoRequest
	(*SimpleResponse)(nil),   // 2: assess.SimpleResponse
	(*ScoreRequest)(nil),     // 3: assess.ScoreRequest
	(*ScoreResponse)(nil),    // 4: assess.ScoreResponse
	(*BasicInfoRequest)(nil), // 5: assess.BasicInfoRequest
	(*EducationRequest)(nil), // 6: assess.EducationRequest
	(*WorkinfoRequest)(nil),  // 7: assess.WorkinfoRequest
	nil,                      // 8: assess.SimpleResponse.DataEntry
	(*apis.Pair)(nil),        // 9: apis.Pair
}
var file_assess_proto_depIdxs = []int32{
	8, // 0: assess.SimpleResponse.data:type_name -> assess.SimpleResponse.DataEntry
	9, // 1: assess.SimpleResponse.DataEntry.value:type_name -> apis.Pair
	3, // 2: assess.AssessService.InitScore:input_type -> assess.ScoreRequest
	3, // 3: assess.AssessService.ScoreInfo:input_type -> assess.ScoreRequest
	5, // 4: assess.AssessService.BasicSave:input_type -> assess.BasicInfoRequest
	6, // 5: assess.AssessService.EducationSave:input_type -> assess.EducationRequest
	7, // 6: assess.AssessService.WorkSave:input_type -> assess.WorkinfoRequest
	0, // 7: assess.AssessService.InitScore:output_type -> assess.OkResponse
	4, // 8: assess.AssessService.ScoreInfo:output_type -> assess.ScoreResponse
	0, // 9: assess.AssessService.BasicSave:output_type -> assess.OkResponse
	0, // 10: assess.AssessService.EducationSave:output_type -> assess.OkResponse
	0, // 11: assess.AssessService.WorkSave:output_type -> assess.OkResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_assess_proto_init() }
func file_assess_proto_init() {
	if File_assess_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_assess_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assess_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assess_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assess_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assess_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assess_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assess_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EducationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assess_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkinfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assess_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assess_proto_goTypes,
		DependencyIndexes: file_assess_proto_depIdxs,
		MessageInfos:      file_assess_proto_msgTypes,
	}.Build()
	File_assess_proto = out.File
	file_assess_proto_rawDesc = nil
	file_assess_proto_goTypes = nil
	file_assess_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AssessServiceClient is the client API for AssessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AssessServiceClient interface {
	InitScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*OkResponse, error)
	ScoreInfo(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	BasicSave(ctx context.Context, in *BasicInfoRequest, opts ...grpc.CallOption) (*OkResponse, error)
	EducationSave(ctx context.Context, in *EducationRequest, opts ...grpc.CallOption) (*OkResponse, error)
	WorkSave(ctx context.Context, in *WorkinfoRequest, opts ...grpc.CallOption) (*OkResponse, error)
}

type assessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessServiceClient(cc grpc.ClientConnInterface) AssessServiceClient {
	return &assessServiceClient{cc}
}

func (c *assessServiceClient) InitScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, "/assess.AssessService/InitScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessServiceClient) ScoreInfo(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, "/assess.AssessService/ScoreInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessServiceClient) BasicSave(ctx context.Context, in *BasicInfoRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, "/assess.AssessService/BasicSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessServiceClient) EducationSave(ctx context.Context, in *EducationRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, "/assess.AssessService/EducationSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessServiceClient) WorkSave(ctx context.Context, in *WorkinfoRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, "/assess.AssessService/WorkSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessServiceServer is the server API for AssessService service.
type AssessServiceServer interface {
	InitScore(context.Context, *ScoreRequest) (*OkResponse, error)
	ScoreInfo(context.Context, *ScoreRequest) (*ScoreResponse, error)
	BasicSave(context.Context, *BasicInfoRequest) (*OkResponse, error)
	EducationSave(context.Context, *EducationRequest) (*OkResponse, error)
	WorkSave(context.Context, *WorkinfoRequest) (*OkResponse, error)
}

// UnimplementedAssessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAssessServiceServer struct {
}

func (*UnimplementedAssessServiceServer) InitScore(context.Context, *ScoreRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitScore not implemented")
}
func (*UnimplementedAssessServiceServer) ScoreInfo(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreInfo not implemented")
}
func (*UnimplementedAssessServiceServer) BasicSave(context.Context, *BasicInfoRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BasicSave not implemented")
}
func (*UnimplementedAssessServiceServer) EducationSave(context.Context, *EducationRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EducationSave not implemented")
}
func (*UnimplementedAssessServiceServer) WorkSave(context.Context, *WorkinfoRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkSave not implemented")
}

func RegisterAssessServiceServer(s *grpc.Server, srv AssessServiceServer) {
	s.RegisterService(&_AssessService_serviceDesc, srv)
}

func _AssessService_InitScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessServiceServer).InitScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assess.AssessService/InitScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessServiceServer).InitScore(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessService_ScoreInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessServiceServer).ScoreInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assess.AssessService/ScoreInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessServiceServer).ScoreInfo(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessService_BasicSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessServiceServer).BasicSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assess.AssessService/BasicSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessServiceServer).BasicSave(ctx, req.(*BasicInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessService_EducationSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EducationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessServiceServer).EducationSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assess.AssessService/EducationSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessServiceServer).EducationSave(ctx, req.(*EducationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessService_WorkSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkinfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessServiceServer).WorkSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assess.AssessService/WorkSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessServiceServer).WorkSave(ctx, req.(*WorkinfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AssessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "assess.AssessService",
	HandlerType: (*AssessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitScore",
			Handler:    _AssessService_InitScore_Handler,
		},
		{
			MethodName: "ScoreInfo",
			Handler:    _AssessService_ScoreInfo_Handler,
		},
		{
			MethodName: "BasicSave",
			Handler:    _AssessService_BasicSave_Handler,
		},
		{
			MethodName: "EducationSave",
			Handler:    _AssessService_EducationSave_Handler,
		},
		{
			MethodName: "WorkSave",
			Handler:    _AssessService_WorkSave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assess.proto",
}
